name: coin_trackr
description: "An app to track your favorites cryptos."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  get_it: ^7.7.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  fpdart: ^1.1.0
  get: ^4.6.6
  cloud_firestore: ^5.2.1
  email_validator: ^3.0.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  mockito: ^5.0.8
  mocktail: ^1.0.4
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
