import 'package:cloud_firestore/cloud_firestore.dart' as firestore;
import 'package:coin_trackr/core/common/managers/navigator_manager.dart';
import 'package:coin_trackr/core/data/datasources/user_local_data_source.dart';
import 'package:coin_trackr/core/domain/repositories/user_repository.dart';
import 'package:coin_trackr/core/domain/usecase/get_current_user_use_case.dart';
import 'package:coin_trackr/core/presentation/providers/navigation_provider.dart';
import 'package:coin_trackr/features/auth/data/datasources/firebase_auth_data_source.dart';
import 'package:coin_trackr/features/auth/data/datasources/firestore_auth_data_source.dart';
import 'package:coin_trackr/features/auth/data/repositories/auth_repository_impl.dart';
import 'package:coin_trackr/core/data/repositories/user_repository_impl.dart';
import 'package:coin_trackr/features/auth/domain/repositories/auth_repository.dart';
import 'package:coin_trackr/features/auth/domain/usecases/login_use_case.dart';
import 'package:coin_trackr/features/auth/domain/usecases/register_use_case.dart';
import 'package:coin_trackr/core/domain/usecase/save_local_user_use_case.dart';
import 'package:coin_trackr/features/auth/presentation/providers/auth_provider.dart';
import 'package:coin_trackr/features/crypto/data/datasources/crypto_remote_datasource.dart';
import 'package:coin_trackr/features/crypto/data/datasources/firestore_crypto_data_source.dart';
import 'package:coin_trackr/features/crypto/data/repositories/crypto_repository_impl.dart';
import 'package:coin_trackr/features/crypto/domain/repositories/crypto_repository.dart';
import 'package:coin_trackr/features/crypto/domain/usecases/delete_favorite_crypto_use_case.dart';
import 'package:coin_trackr/features/crypto/domain/usecases/get_crypto_list_use_case.dart';
import 'package:coin_trackr/features/crypto/domain/usecases/get_favorites_cryptos_use_case.dart';
import 'package:coin_trackr/features/crypto/domain/usecases/set_favorite_crypto_use_case.dart';
import 'package:coin_trackr/features/crypto/presentation/providers/crypto_provider.dart';
import 'package:coin_trackr/features/profile/data/datasources/firebase_profile_data_source.dart';
import 'package:coin_trackr/features/profile/data/datasources/firestore_profile_data_source.dart';
import 'package:coin_trackr/features/profile/data/repositories/profile_repository_impl.dart';
import 'package:coin_trackr/features/profile/domain/repositories/profile_repository.dart';
import 'package:coin_trackr/features/profile/domain/usecases/update_password_use_case.dart';
import 'package:coin_trackr/features/profile/domain/usecases/update_user_use_case.dart';
import 'package:coin_trackr/features/profile/presentation/providers/profile_provider.dart';
import 'package:firebase_auth/firebase_auth.dart' as firebase;
import 'package:get_it/get_it.dart';
import 'package:http/http.dart' as http;

part 'injection_container.dart';
